---

- name: Ensure GPG keys are configured
  shell: "{{ gpg_configuration_command }}"
  changed_when: false
  failed_when: false

- name: Ensure gpgcheck is globally activated
  replace:
   name: "{{ global_gpg_check }}"
   regexp: "^gpgcheck=0"
   replace: "gpgcheck=1"

- name: Ensure gpgcheck is globally activated | determining path to all repos
  find: 
    paths: "{{ path_to_repos }}"
    patterns: "*.repo"
  register: yum_repos
  changed_when: no

- name: Ensure gpgcheck is globally activated 
  replace: 
    name: "{{ item.path }}" 
    regexp: "^gpgcheck=0"
    replace: "gpgcheck=1"
  with_items:
  - "{{ yum_repos.files }}"  

