---
- name: Ensure SELinux is not disabled in bootloader configuration"
  replace:
      dest: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
      follow: yes
  register: selinux_grub_patch
  ignore_errors: yes
  notify: generate new grub config

- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: Ensure SETroubleshoot is not installed
  yum:
    name: setroubleshoot
    state: absent