---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- name: Upgrade repo packages
  become: true
  yum: 
   name: "*"
   state: latest
  when:
  - ansible_os_family == 'RedHat'

- name: Upgrade repo packages
  become: true
  apt:
   upgrade: yes
   update_cache: yes
   cache_valid_time: 86400
  when:
  - ansible_os_family == 'Debian'

- name: Install necessary packages for audit
  yum:
    name: "{{ packages }}"
    state: latest
  when:  
   - ansible_os_family == 'RedHat'

- include_tasks: section1/unloading_filesystems.yml
  become: yes
  when: 
   - ansible_os_family == 'RedHat'

- include_tasks: section1/configure_partitions.yml
  become: yes
  when: 
  - ansible_os_family == 'RedHat'

- include_tasks: section1/stickykey.yml
  become: yes
  when: 
  - ansible_os_family == 'RedHat'

- include_tasks: section1/disabling_automounting.yml
  become: yes
  when: 
  - ansible_os_family == 'RedHat'

- include_tasks: section1/repo.yml
  become: yes
  when: 
  - ansible_os_family == 'RedHat'

- include_tasks: section1/filesystem_integrity.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'  

- include_tasks: section1/secure_boot_settings.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'  

- include_tasks: section1/authentication.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section1/coredumps.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section1/XD-NX.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section1/aslr_enabled.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section1/prelink.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section1/SELinux.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section1/motd_permissions.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section1/yum_security_updates.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section2/inetd.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section2/time_synchronization.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section2/remove-xwindow.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section2/postfix.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section2/disabling_services.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section2/service_clients.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section3/network_parameters.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section3/network_parameters_host_router.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section3/logging_ICMP.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section3/disable_IPv6.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section3/tcp_wrappers.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section3/firewalld.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section4/auditd_config.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section4/grub_audit.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section4/audit_rules.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section4/enable_rsyslog.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section5/enable_cron.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section5/sshd_permissions.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'

- include_tasks: section5/pam_configuration.yml
  become: yes
  when:
  - ansible_os_family == 'RedHat'




