---
- name: Make sure user and password for grub has been made (Please set password using grub2-setpassword encase of failure)
  stat:
    path: "{{ path_to_grubuser }}"
  register: stat_result
  failed_when: stat_result.stat.exists == False 

- name: Ensure permissions on bootloader config are configured
  file:
    path: "{{ path_to_grub }}"
    owner: root
    group: root
    mode: og-rwx

- name: Ensure permissions on bootloader config are configured
  file:
    path: "{{ path_to_grubuser }}"
    owner: root
    group: root
    mode: og-rwx

