---
- name: "SCORED | 2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
   dest: /etc/postfix/main.cf
   regexp: "^(#)?inet_interfaces"
   line: "inet_interfaces = localhost"