---
# handlers file for CIS-Benchmarks-Hardening-Linux
- name: restart tmp.mount
  become: yes
  systemd:
      name: tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: reloaded

- name: generate new grub config
  become: yes
  command: grub2-mkconfig -o "{{ grub_cfg.stat.lnk_source }}"

- name: restart chrony
  service:
    name: "{{ name_of_chrony_service }}" 
    state: restarted

- name: flush ipv4 tables
  become: yes
  sysctl:
      name: net.ipv4.route.flush
      value: 1
      sysctl_set: yes

- name: reload auditd
  systemd:
    name: auditd
    enabled: yes
    state: started

- name: reload sshd
  become: yes
  systemd:
    name: sshd
    enabled: yes
    state: restarted

- name: restart firewalld 
  systemd:
    name: firewalld
    enabled: yes
    state: restarted