 
- name: Verify or create auditd.conf
  file: 
    path: "{{ auditd_conf }}"
    owner: root
    group: root
    mode: 400
    state: touch
  changed_when: no

- name: Ensure audit log storage size is configured"
  lineinfile:
      dest: "{{ auditd_conf }}"
      regexp: "^max_log_file( |=)"
      line: "max_log_file = {{ max_log_size }}"
      state: present
  notify: reload auditd

- name: Ensure system is disabled when audit logs are full
  lineinfile:
    path: "{{ auditd_conf }}"
    regexp: "space_left_action "
    line: '^#?space_left_action = email\s*='
  notify: reload auditd

- name: Ensure system is disabled when audit logs are full
  lineinfile:
    path: "{{ auditd_conf }}"
    regexp: "action_mail_acct "
    line: '^#?action_mail_acct = root\s*='
  notify: reload auditd

- name: Ensure system is disabled when audit logs are full
  lineinfile:
    path: "{{ auditd_conf }}"
    regexp: "admin_space_left_action "
    line: '^#?admin_space_left_action = halt\s*='
  notify: reload auditd

- name: Ensure audit logs are not automatically
  lineinfile:
    path: "{{ auditd_conf }}"
    regexp: "max_log_file_action"
    line: '^#?max_log_file_action = keep_logs \s*='
  notify: reload auditd
