---
- name: Ensure auditing for processes that start prior to auditd is enabled
  replaces: 
    path: "{{ path_to_grub }}"
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
    replace: '\1"\2 audit=1"'
    follow: yes
  notify: generate new grub config